name: C++ Linter

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Build Compilation Database
        run: platformio run -e esp32 --target compiledb
      - name: Check clang-format syntax
        run: |
          # Verifica se o arquivo .clang-format é válido
          clang-format --style=file --dump-config > /dev/null
          echo "clang-format configuration is valid"
      - name: Fix line endings
        run: |
          # Converte line endings para LF (Unix) para evitar problemas com clang-format
          find src/ -name "*.hpp" -o -name "*.cpp" | xargs sed -i 's/\r$//'
          echo "Line endings converted to LF"
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: ''
          database: compile_commands.json
          files-changed-only: true
          no-lgtm: false
          step-summary: true
          file-annotations: true
          tidy-review: true
          format-review: true
          thread-comments: 'update'
